### ISSUE TITLE
如果 max30102 初始化过程中偶然 IIC read 失败，会导致 IIC 初始化的内容无法在该驱动中正确释放。

### ISSUE THREAD

**Issue by gengyuchao** [hepingood/max30102#5]
https://github.com/hepingood/max30102/blob/5184e0290f4f90f0f5a61e996563d807cd22bf96/src/driver_max30102.c#L163,L169

**Comment by libdriver** [comment]
Thank you very much for your suggestion. At present, we have fixed this bug. At the same time, thank you very much for your esp32 project. We will consolidate your project as soon as possible and add you to the list of LibDriver contributors.

非常感谢您的建议，目前我们已经修复此Bug。同时也非常感谢您提供的ESP32工程，我们会尽快整理合并您的工程，并将您加入到LibDriver贡献者行列。
